# Site settings
title: Holy Hues
description: Your pocket Bible with a creative twist
url: "https://holyhues.app"
baseurl: ""
version: 1.1

# Build settings
markdown: kramdown
permalink: pretty
exclude: [README.md, Gemfile, Gemfile.lock]

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  experiences:
    output: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-redirect-from 