# Site settings
title: Holy Hues
description: Holy Hues is your pocket Bible with a creative twist. Browse verses with intuitive swipes, explore multiple translations, and create beautiful verse wallpapers.
url: "https://holyhues.app"
keywords: "bible app, daily bible verse, christian app, scripture wallpapers, holy hues, bible study tool, pocket bible, bible verses, inspirational verses, custom bible backgrounds, bible with fonts, creative bible, bible translations app, kjv bible, niv bible, bible wallpapers, christian wallpapers, bible quotes app, daily scripture, bible with customization, share bible verses, bible app with colors, bible chapters, bible with gradients, bible inspiration app, christian daily devotion, bible reading app, mobile bible, faith app, bible on the go, personalized scripture"
baseurl: ""
version: 1.1

# Build settings
markdown: kramdown
permalink: pretty
exclude: [README.md, Gemfile, Gemfile.lock]

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  experiences:
    output: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-redirect-from 